### ISSUE TITLE
build explanation

### ISSUE THREAD

**Issue by sbowman-mitre** [jython/jython3#24]
Hi, it's not clear from just examining the files in the repo how to build the code. There is a build.xml, so ant? Then there is also a maven directory, but with no fully formed pom in it. Can you clarify how to go about building the code and run the tests?

**Comment by fwierzbicki** [comment]
Yep, ant is the current build system, and the default when calling "ant" is to build a dev distribution so that you can run it like : ./dist/bin/jython

Note that jython3 is pre-alpha!

**Comment by fwierzbicki** [comment]
Oh and the maven directory is strictly for creating packages to upload to the maven repository - and pretty much no one other than me ever uses it :) -- there are no current plans to make Jython a maven project, but we are strongly considering switching to gradle for builds.

**Comment by sbowman-mitre** [comment]
Awesome, thanks.
