### ISSUE TITLE
This can support python3.5 third-party libraries? For example: numpy, if so, how to use

### ISSUE THREAD

**Issue by ganhb** [jython/jython3#35]
As the title shows

**Comment by Stewori** [comment]
NumPy uses C-extensions which are traditionally not supported by Jython. That said, NumPy is workable on Jython to some extend using [JyNI](https://github.com/Stewori/JyNI), however there is no JyNI 3 yet. Development of JyNI 3 will not start before Jython 3 itself reaches at least beta state.
