### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by Richienb** [jython/jython3#39]
After `git clone`ing the repository and `cd`ing to it, what do I run next?

**Comment by jeff5** [comment]
`ant`

There's a bit of a guide (for 2.7 really) [here](https://jython-devguide.readthedocs.io/en/latest/). Assuming we're talking about Jython 3, you should realise:
1. It is an experimental fork.
2. Jython 3 moved rapidly in its own direction then halted.
3. Jython 2.7 moved slowly on from the same point, and to port those changes to 3 is hard.
