### ISSUE TITLE
where can i find the most advanced and stable version jython?

### ISSUE THREAD

**Issue by xforward7** [jython/jython3#40]
Dear all old buddy ,   where can i find the most advanced and stable version jython?

**Comment by Stewori** [comment]
The most stable Jython version is still the curren Jython 2.7 master branch: https://github.com/jythontools/jython. It's still 2.7 but has seen much more development recently than this Jython 3 *sandbox*. It's also significantly more advanced than the latest release, i.e. 2.7.1. A next release 2.7.2 is somewhat ahead, but no date is set.

**Comment by lrevnic** [comment]
@Stewori is there any estimation on when Jython 3 will be released?

**Comment by xforward7** [comment]
> The most stable Jython version is still the current Jython 2.7 master branch: https://github.com/jythontools/jython. It's still 2.7 but has seen much more development recently than this Jython 3 _sandbox_. It's also significantly more advanced than the latest release, i.e. 2.7.1. A next release 2.7.2 is somewhat ahead, but no date is set.

tks  your reply, i am looking forward 3

**Comment by Stewori** [comment]
You may want to have a look at [the latest mail on this topic](https://sourceforge.net/p/jython/mailman/message/37063723/) if you haven't seen it yet.
