### ISSUE TITLE
when are jython3 download?

### ISSUE THREAD

**Issue by yanzhao77** [jython/jython3#44]
The last update was three years ago. Does that mean that the update has stopped？

**Comment by jeff5** [comment]
Last update is here: https://github.com/jython/jython3/commit/def4f8ec47cb7a9c799ea4c745f12badf92c5769 to the [README]{https://github.com/jython/jython3#readme). That should make things clear.

There's an attempt at a Jython 3 new core interpreter at https://github.com/jython/jython/tree/main but all it does is run some unit tests.
