### ISSUE TITLE
org.python.antlr.AnalyzingParser.java Wox loss problem

### ISSUE THREAD

**Issue by kamalyes** [jython/jython3#47]
You have seen that the official website of jython said it would launch version 3.8. Is this project still under maintenance? I pulled your master branch and found that some classes were missing. I look forward to your reply
![image](https://user-images.githubusercontent.com/40486003/224467420-af5f4a43-1764-4362-b5ef-0ad3e4dcf8fe.png)

**Comment by Stewori** [comment]
The readme states that this repo is legacy. @jeff5 maybe it should be more prominently...? E.g. rename the repo to something like "jython3 (legacy attempt)". That said, @kamalyes see

https://github.com/jython/jython/issues/235#issuecomment-1453149851
https://github.com/jython/jython/issues/198
https://www.jython.org/jython-3-roadmap

**Comment by jeff5** [comment]
> You have seen that the official website of jython said it would launch version 3.8. Is this project still under maintenance?

This repo isn't maintained, but the project is.

Jython 3.8 (it might be 3.11) will appear under the main jython repo. There is a `main` branch quietly growing there but it is fairly immature (and not the default branch you see).

**Comment by jeff5** [comment]
@Stewori : I strengthened the README only last week in the hope it would be enough. (One only has to scroll down to get a link to [the real Jython 3 in development](https://github.com/jython/jython/tree/main).) I don't want to disparage the original attempt, just avoid confusion.

A name change is a good idea. It does seem to be all people see. In that case I favour taking the word jython and maybe 3 out of the repo name. :/

I was forced to change the name on https://github.com/jython/jython-bad-history, and links within GitHub issues changed magically. Forks looked a little odd and may have broken. External links would break, but perhaps deservedly. (With `jython-bad-history` there would immediately be a replacement for external links to land on.)

**Comment by kamalyes** [comment]
" Thank you, I find the main branch, under the jython and commit id is 8 be597df53991b42f20a0104cb8f543ff00cc6df, but I found that the middle about python2.7 related content, don't know whether there will be affected



***@***.***
 
From: Jeff Allen
Date: 2023-03-12 16:39
To: jython/jython3
CC: kamalyes; Mention
Subject: Re: [jython/jython3] org.python.antlr.AnalyzingParser.java Wox loss problem (Issue #47)
@Stewori : I strengthened the README only last week in the hope it would be enough. (One only has to scroll down to get a link to the real Jython 3 in development.) I don't want to disparage the original attempt, just avoid confusion.
A name change is a good idea. It does seem to be all people see. In that case I favour taking the word jython and maybe 3 out of the repo name. :/
I was forced to change the name on https://github.com/jython/jython-bad-history, and links within GitHub issues changed magically. Forks looked a little odd and may have broken. External links would break, but perhaps deservedly. (With jython-bad-history there would immediately be a replacement for external links to land on.)

**Comment by jeff5** [comment]
Yes, that's the latest commit. https://github.com/jython/jython/commit/8be597df53991b42f20a0104cb8f543ff00cc6df I am developing my understanding of the next part of the work in another repo.

> I found that the middle about python2.7 related content, don't know whether there will be affected

I'm sorry, I didn't understand that. Could you re-phrase the question?
