### ISSUE TITLE
Wrong column number when parsing single character parameter

### ISSUE THREAD

**Issue by khatchad** [jython/jython3#48]
I'm parsing the following file:
```python
import tensorflow as tf

def add(a, b):
  return a + b


c = add(tf.ones([1, 2]), tf.ones([2, 2]))  #  [[2., 2.], [2., 2.]]

```
When we get to parameter `a`, I see the `CommonToken` representing `a` as follows:
```
[@12,33:33='a',<63>,3:8]
```
Particularly, `charPositionInLine` for `a` is 8, but it should be 9. Also, there's one character, so we should see `33:34` as the start and end column.

**Comment by jeff5** [comment]
Sorry, the code in this repo is not maintained. See https://github.com/jython/jython3#readme , which also refers to Jython 3 work.
